### ISSUE TITLE
Add more examples

### ISSUE THREAD

**Issue by vrothberg** [containers/BuildSourceImage#49]
We should add some more use-case oriented examples to give users/readers a better idea of what they can do if their needs are met.

**Comment by vbatts** [comment]
include `unpack` subcommand here

**Comment by fatherlinux** [comment]
Pull binary image
`skope pull...`

Build source  image from binary image
`podman run -it -v $(pwd)/output/:/output/ -v $(pwd)/SRCRPMS/:/data/ -u $(id -u) quay.io/ctrs/bsi -s /data/ -o /output/`

Push source image to registry
`skopeo push`

Pull source image from registry
`Skopeo pull... (to local OCI directory)`

@vbatts couldnt' #1 above just unpack on the pull, since it's skopeo?

**Comment by vbatts** [comment]
funny, Valentin and I chatted about this thing today.
We talked about separating the pull/push from the tool, leaving that
wholly up to skopeo, even if we include a skopeo version in the
container we ship, it would be a different invocation to a container,
that just has a common data volume.
```bash
skopeo copy docker://${ref}:${tag} oci:./...
bsi unpack oci:./... ./image-rootfs/
bsi build -r ./image-rootfs/ -s ./data/ -o ./output/
skopeo copy oci:./output/ docker://${ref}:${tag}-source
```
I don't terribly mind this, and it does have the benefit of letting the
caller replace the version of skopeo or whatever. But this approach has
the drawback of being a clunky user experience where they need to "just
know" the steps to do, in order to get it correct.

either way, allowing easier pass through of auth/creds to skopeo for
pull/push is nice enough.
And perhaps the way we're using `skopeo inspect` currently is not even
needed?
